export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED'

export const getCategories = () => ({
  type: GET_CATEGORIES_REQUESTED,
});
